nelmio_api_doc:
  documentation:
    servers:
      - url: https://127.0.0.1:8000
    info:
      title: Documentation api Application bedoo
      description: APIs pour toute la gestion du projet bedoo
      version: 1.0.0

    security:
      - BearerAuth: []

  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc